// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB4E3fwGJdVP-ZEPF9XPpeiaetMhzaGzDA',
    appId: '1:286081622195:web:7a09e8c53e81a9f13890c6',
    messagingSenderId: '286081622195',
    projectId: 'joblinker-c7ceb',
    authDomain: 'joblinker-c7ceb.firebaseapp.com',
    storageBucket: 'joblinker-c7ceb.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBOICiVqkibFwhkIj8Hz9tnE8olwR8UX78',
    appId: '1:286081622195:android:75370b8857b6535c3890c6',
    messagingSenderId: '286081622195',
    projectId: 'joblinker-c7ceb',
    storageBucket: 'joblinker-c7ceb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAslHtvP07qVdTMN14AWYpqCVjPXZfARb8',
    appId: '1:286081622195:ios:b9bf6626ddfbcdb43890c6',
    messagingSenderId: '286081622195',
    projectId: 'joblinker-c7ceb',
    storageBucket: 'joblinker-c7ceb.appspot.com',
    iosBundleId: 'com.example.joblinker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAslHtvP07qVdTMN14AWYpqCVjPXZfARb8',
    appId: '1:286081622195:ios:b9bf6626ddfbcdb43890c6',
    messagingSenderId: '286081622195',
    projectId: 'joblinker-c7ceb',
    storageBucket: 'joblinker-c7ceb.appspot.com',
    iosBundleId: 'com.example.joblinker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB4E3fwGJdVP-ZEPF9XPpeiaetMhzaGzDA',
    appId: '1:286081622195:web:ee766b971061a94c3890c6',
    messagingSenderId: '286081622195',
    projectId: 'joblinker-c7ceb',
    authDomain: 'joblinker-c7ceb.firebaseapp.com',
    storageBucket: 'joblinker-c7ceb.appspot.com',
  );
}
